version: "2"
services:
  router:
    image: nginx:latest
    volumes:
      - ./nginx-routing/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-routing/templates:/var/www:ro
    ports:
      - "80:80"
    # restart: on-failure

    depends_on:
      - mulambdati

  mulambdati:
    extends:
      file: mulambdati/docker-compose.yml
      service: mulambdati
