version: "2"
services:
  router:
    build: router
    volumes:
      - ./ssl/certs:/etc/letsencrypt:ro
      - ./ssl/challenge-data:/var/www/certbot:ro

      - ./router/nginx/logs:/var/log/nginx
      - ./morse-trainer:/var/www/static/coral.shoes/morse-trainer

      - ./ilo-pi-ante-toki/static:/var/www/static/ilo-pi-ante-toki:ro
      - ./ilo-pi-ante-toki/save:/var/www/static/ilo-pi-ante-toki-save:ro

      - ./trash:/var/www/static/trash:ro

    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    init: true

  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./ssl/certs:/etc/letsencrypt
      - ./ssl/challenge-data:/var/www/certbot
    init: true

  ilo-pi-ante-toki:
    extends:
      file: ilo-pi-ante-toki/docker-compose.yml
      service: ilo-pi-ante-toki
    init: true

  jsless:
    build: jsless-server
    ports:
      - "13080:13080"
    restart: on-failure
    init: true

  george-status:
    build: george-status
    volumes:
      - ./george-status//:/usr/src/app
    ports:
      - "9080:9080"
    restart: on-failure
    init: true

