version: "2"
services:
  router:
    build: nginx-routing
    volumes:
      - ./nginx-routing/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-routing/static:/var/www/static:ro

      - ./ssl/certs:/etc/letsencrypt:ro
      - ./ssl/conf:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    depends_on:
      - mulambdati
      - citrons_server
      - certbot_wrapper

  certbot_wrapper:
    build: certbot_wrapper
    volumes:
      - ./ssl/certs:/etc/letsencrypt
      - ./ssl/conf:/var/www/certbot

  mulambdati:
    extends:
      file: mulambdati/docker-compose.yml
      service: mulambdati

  citrons_server:
    extends:
      file: citrons-server/docker-compose.yml
      service: blattidus

  ilo-pi-ante-toki:
    extends:
      file: ilo-pi-ante-toki/docker-compose.yml
      service: ilo-pi-ante-toki

