external_links = []

[[blogs]]
identifier = "brainfuck-quine"
title = "quines, and brainfuck"
tagline = "exploring how quines work, and how to make one"
written-at = 2023-04-27

[[blogs-wip]]
title = "softdouble.c"
tagline = "implementing doubles when all you have is floats"

[[blogs-wip]]
title = "nojs cookie clicker"
tagline = "javascript is a fundamental part of any interactive site — what if we just didn't use it?"

[[blogs-wip]]
title = "nontrivial programs in brainfuck — a calculator"
tagline = "exploring the fundamentals of computation in possibly the worst environment imaginable"


[[internal_links]]
title = "coral morse trainer"
href = "morse-trainer"
desc = "interactive morse code trainer, made because i wanted to learn morse :)"

[[internal_links]]
title = "nojs cookie clicker"
href = "jsless"
desc = "simple cookie clicker clone in the browser, interactive despite not using javascript"


